name: Generate Codecov Report

on:
  repository_dispatch:
    types: [codecov-report-command]

env:
  EXAMPLES_FOLDER: examples

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        include:
          - os: macos-latest
            label: osx-arm64
            prefix: /Users/runner/miniconda3/envs/biobuddy
    name: codecov
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v4
        with:
          reactions: eyes

      - name: Checkout code with submodule
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest

      - name: Set up Python
        run: |
          conda install -cconda-forge python=3.11.11 pip 

      - name: Install dependencies
        run: | 
          pip install . && pip uninstall -y biobuddy
          pip install scipy==1.15.1 numpy==1.25.2 lxml ezc3d

      - name: Install test dependencies
        run: |
          pip install pytest pytest-cov codecov pyomeca
          conda install -c opensim-org opensim=4.5.1
          conda install -c conda-forge biorbd=1.11.2 deepdiff

      - name: Run tests with code coverage
        run: pytest -v --color=yes --cov-report=xml --cov=biobuddy tests

      - name: Send Codecov report
        id: archive
        uses: codecov/codecov-action@v5
        with:
          path: .covergage
          if-no-files-found: error
          fail_ci_if_error: true
          verbose: true

      - name: Generate XML report
        run: |
          coverage xml
          coverage report -m

      - uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true
