name: Slash Command

on:
  issue_comment:
    types: [created]

env:
  EXAMPLES_FOLDER: examples

jobs:
  slash-command:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != null && contains(github.event.comment.body, '/codecov')
    steps:
      - name: Send Codecov report
        id: archive
        uses: codecov/codecov-action@v5
        with:
          path: .covergage
          if-no-files-found: error
          fail_ci_if_error: true
          verbose: true
        if: matrix.os == 'ubuntu-latest'

      - name: Generate XML report
        run: |
          coverage xml
          coverage report -m

      - uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true
